# ============================================================================
# infra.mk — wmaker-crm infra layer (NOT the build system)
# ----------------------------------------------------------------------------
# The C core is autotools: the top-level `Makefile` is generated by
# `./configure` and is gitignored (`*Makefile`). So our thin infra layer — the
# rebase ritual and the headless container image — lives here and is invoked
# explicitly, never shadowing the sacred build:
#
#     make -f infra.mk help
#
# House style mirrors tacitness/{tsctl,wmaker-ng}: self-documenting `##` help,
# no version numbers stored in-tree.
# ============================================================================

.DEFAULT_GOAL := help
SHELL         := /bin/bash

ROOT_DIR := $(shell git rev-parse --show-toplevel 2>/dev/null || pwd)

# ── Help ──────────────────────────────────────────────────────────────────────
.PHONY: help
help: ## Show this help
	@echo "wmaker-crm infra targets (build the WM itself with: ./autogen.sh && ./configure && make)"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

# ── Rebase ritual ─────────────────────────────────────────────────────────────
# Fetch upstream (repo.or.cz/wmaker-crm) and rebase our infra/patch layer onto
# it on a fresh branch. Never touches master; never pushes. The monthly CI
# version lives in .github/workflows/upstream-sync.yml.
.PHONY: rebase
rebase: ## Rebase our layer onto upstream Window Maker (scripts/rebase-upstream.sh)
	@scripts/rebase-upstream.sh
